# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Base cross-loader settings.
minecraft_version=1.20.1
parchment_version=2023.09.03
# Mod Properties
maven_group=org.blocovermelho
archives_base_name=ae2emi
mod_id=ae2emi
# Dependencies

### Fabric Setup
### To update the versions, see https://fabricmc.net/develop/

# Version to be used for the loom plugin. Not currently set to 1.+ since 1.16 seems to be a bit broken.
# I'll wait for an announcement of the release and test locally before updating it.
loom_version=1.16-SNAPSHOT
# Fabric loader is version agnostic.
# We should keep this the same across minecraft versions unless something horrible happens.
fabric_loader_version=0.18.6
# This is the fabric dependency thats most likely to change.
fabric_api_version=0.92.7+1.20.1
fabric_kotlin_version=1.13.10+kotlin.2.3.20
